// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `FinancialNews.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FinancialNews;

public final class FinancialNewsReceiverPrxHelper extends Ice.ObjectPrxHelperBase implements FinancialNewsReceiverPrx
{
    private static final String __exchangeRate_name = "exchangeRate";

    public void exchangeRate(float rate, Currency curr1, Currency curr2)
    {
        exchangeRate(rate, curr1, curr2, null, false);
    }

    public void exchangeRate(float rate, Currency curr1, Currency curr2, java.util.Map<String, String> __ctx)
    {
        exchangeRate(rate, curr1, curr2, __ctx, true);
    }

    private void exchangeRate(float rate, Currency curr1, Currency curr2, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "exchangeRate", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _FinancialNewsReceiverDel __del = (_FinancialNewsReceiverDel)__delBase;
                    __del.exchangeRate(rate, curr1, curr2, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_exchangeRate(float rate, Currency curr1, Currency curr2)
    {
        return begin_exchangeRate(rate, curr1, curr2, null, false, null);
    }

    public Ice.AsyncResult begin_exchangeRate(float rate, Currency curr1, Currency curr2, java.util.Map<String, String> __ctx)
    {
        return begin_exchangeRate(rate, curr1, curr2, __ctx, true, null);
    }

    public Ice.AsyncResult begin_exchangeRate(float rate, Currency curr1, Currency curr2, Ice.Callback __cb)
    {
        return begin_exchangeRate(rate, curr1, curr2, null, false, __cb);
    }

    public Ice.AsyncResult begin_exchangeRate(float rate, Currency curr1, Currency curr2, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_exchangeRate(rate, curr1, curr2, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_exchangeRate(float rate, Currency curr1, Currency curr2, Callback_FinancialNewsReceiver_exchangeRate __cb)
    {
        return begin_exchangeRate(rate, curr1, curr2, null, false, __cb);
    }

    public Ice.AsyncResult begin_exchangeRate(float rate, Currency curr1, Currency curr2, java.util.Map<String, String> __ctx, Callback_FinancialNewsReceiver_exchangeRate __cb)
    {
        return begin_exchangeRate(rate, curr1, curr2, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_exchangeRate(float rate, Currency curr1, Currency curr2, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __exchangeRate_name, __cb);
        try
        {
            __result.__prepare(__exchangeRate_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeFloat(rate);
            curr1.__write(__os);
            curr2.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_exchangeRate(Ice.AsyncResult __result)
    {
        __end(__result, __exchangeRate_name);
    }

    private static final String __interestRate_name = "interestRate";

    public void interestRate(float rate, Currency curr)
    {
        interestRate(rate, curr, null, false);
    }

    public void interestRate(float rate, Currency curr, java.util.Map<String, String> __ctx)
    {
        interestRate(rate, curr, __ctx, true);
    }

    private void interestRate(float rate, Currency curr, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "interestRate", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _FinancialNewsReceiverDel __del = (_FinancialNewsReceiverDel)__delBase;
                    __del.interestRate(rate, curr, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_interestRate(float rate, Currency curr)
    {
        return begin_interestRate(rate, curr, null, false, null);
    }

    public Ice.AsyncResult begin_interestRate(float rate, Currency curr, java.util.Map<String, String> __ctx)
    {
        return begin_interestRate(rate, curr, __ctx, true, null);
    }

    public Ice.AsyncResult begin_interestRate(float rate, Currency curr, Ice.Callback __cb)
    {
        return begin_interestRate(rate, curr, null, false, __cb);
    }

    public Ice.AsyncResult begin_interestRate(float rate, Currency curr, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_interestRate(rate, curr, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_interestRate(float rate, Currency curr, Callback_FinancialNewsReceiver_interestRate __cb)
    {
        return begin_interestRate(rate, curr, null, false, __cb);
    }

    public Ice.AsyncResult begin_interestRate(float rate, Currency curr, java.util.Map<String, String> __ctx, Callback_FinancialNewsReceiver_interestRate __cb)
    {
        return begin_interestRate(rate, curr, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_interestRate(float rate, Currency curr, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __interestRate_name, __cb);
        try
        {
            __result.__prepare(__interestRate_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeFloat(rate);
            curr.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_interestRate(Ice.AsyncResult __result)
    {
        __end(__result, __interestRate_name);
    }

    public static FinancialNewsReceiverPrx checkedCast(Ice.ObjectPrx __obj)
    {
        FinancialNewsReceiverPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof FinancialNewsReceiverPrx)
            {
                __d = (FinancialNewsReceiverPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    FinancialNewsReceiverPrxHelper __h = new FinancialNewsReceiverPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static FinancialNewsReceiverPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        FinancialNewsReceiverPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof FinancialNewsReceiverPrx)
            {
                __d = (FinancialNewsReceiverPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    FinancialNewsReceiverPrxHelper __h = new FinancialNewsReceiverPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static FinancialNewsReceiverPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        FinancialNewsReceiverPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    FinancialNewsReceiverPrxHelper __h = new FinancialNewsReceiverPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static FinancialNewsReceiverPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        FinancialNewsReceiverPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    FinancialNewsReceiverPrxHelper __h = new FinancialNewsReceiverPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static FinancialNewsReceiverPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        FinancialNewsReceiverPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof FinancialNewsReceiverPrx)
            {
                __d = (FinancialNewsReceiverPrx)__obj;
            }
            else
            {
                FinancialNewsReceiverPrxHelper __h = new FinancialNewsReceiverPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static FinancialNewsReceiverPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        FinancialNewsReceiverPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            FinancialNewsReceiverPrxHelper __h = new FinancialNewsReceiverPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::FinancialNews::FinancialNewsReceiver",
        "::Ice::Object"
    };

    public static String ice_staticId()
    {
        return __ids[0];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _FinancialNewsReceiverDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _FinancialNewsReceiverDelD();
    }

    public static void __write(IceInternal.BasicStream __os, FinancialNewsReceiverPrx v)
    {
        __os.writeProxy(v);
    }

    public static FinancialNewsReceiverPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            FinancialNewsReceiverPrxHelper result = new FinancialNewsReceiverPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
