// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `FinancialNews.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FinancialNews;

public final class FinancialNewsServerPrxHelper extends Ice.ObjectPrxHelperBase implements FinancialNewsServerPrx
{
    private static final String __registerForNews_name = "registerForNews";

    public void registerForNews(FinancialNewsReceiverPrx subscriber)
    {
        registerForNews(subscriber, null, false);
    }

    public void registerForNews(FinancialNewsReceiverPrx subscriber, java.util.Map<String, String> __ctx)
    {
        registerForNews(subscriber, __ctx, true);
    }

    private void registerForNews(FinancialNewsReceiverPrx subscriber, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "registerForNews", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __delBase = __getDelegate(false);
                    _FinancialNewsServerDel __del = (_FinancialNewsServerDel)__delBase;
                    __del.registerForNews(subscriber, __ctx, __observer);
                    return;
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_registerForNews(FinancialNewsReceiverPrx subscriber)
    {
        return begin_registerForNews(subscriber, null, false, null);
    }

    public Ice.AsyncResult begin_registerForNews(FinancialNewsReceiverPrx subscriber, java.util.Map<String, String> __ctx)
    {
        return begin_registerForNews(subscriber, __ctx, true, null);
    }

    public Ice.AsyncResult begin_registerForNews(FinancialNewsReceiverPrx subscriber, Ice.Callback __cb)
    {
        return begin_registerForNews(subscriber, null, false, __cb);
    }

    public Ice.AsyncResult begin_registerForNews(FinancialNewsReceiverPrx subscriber, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_registerForNews(subscriber, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_registerForNews(FinancialNewsReceiverPrx subscriber, Callback_FinancialNewsServer_registerForNews __cb)
    {
        return begin_registerForNews(subscriber, null, false, __cb);
    }

    public Ice.AsyncResult begin_registerForNews(FinancialNewsReceiverPrx subscriber, java.util.Map<String, String> __ctx, Callback_FinancialNewsServer_registerForNews __cb)
    {
        return begin_registerForNews(subscriber, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_registerForNews(FinancialNewsReceiverPrx subscriber, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __registerForNews_name, __cb);
        try
        {
            __result.__prepare(__registerForNews_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            FinancialNewsReceiverPrxHelper.__write(__os, subscriber);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public void end_registerForNews(Ice.AsyncResult __result)
    {
        __end(__result, __registerForNews_name);
    }

    public static FinancialNewsServerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        FinancialNewsServerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof FinancialNewsServerPrx)
            {
                __d = (FinancialNewsServerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    FinancialNewsServerPrxHelper __h = new FinancialNewsServerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static FinancialNewsServerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        FinancialNewsServerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof FinancialNewsServerPrx)
            {
                __d = (FinancialNewsServerPrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    FinancialNewsServerPrxHelper __h = new FinancialNewsServerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static FinancialNewsServerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        FinancialNewsServerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    FinancialNewsServerPrxHelper __h = new FinancialNewsServerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static FinancialNewsServerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        FinancialNewsServerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    FinancialNewsServerPrxHelper __h = new FinancialNewsServerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static FinancialNewsServerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        FinancialNewsServerPrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof FinancialNewsServerPrx)
            {
                __d = (FinancialNewsServerPrx)__obj;
            }
            else
            {
                FinancialNewsServerPrxHelper __h = new FinancialNewsServerPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static FinancialNewsServerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        FinancialNewsServerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            FinancialNewsServerPrxHelper __h = new FinancialNewsServerPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::FinancialNews::FinancialNewsServer",
        "::Ice::Object"
    };

    public static String ice_staticId()
    {
        return __ids[0];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _FinancialNewsServerDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _FinancialNewsServerDelD();
    }

    public static void __write(IceInternal.BasicStream __os, FinancialNewsServerPrx v)
    {
        __os.writeProxy(v);
    }

    public static FinancialNewsServerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            FinancialNewsServerPrxHelper result = new FinancialNewsServerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
