// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `FinancialNews.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FinancialNews;

public interface FinancialNewsReceiver extends Ice.Object,
                                               _FinancialNewsReceiverOperations, _FinancialNewsReceiverOperationsNC
{
    public static final long serialVersionUID = 323181438120177252L;
}
