// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `FinancialNews.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FinancialNews;

public final class FinancialNewsReceiverHolder extends Ice.ObjectHolderBase<FinancialNewsReceiver>
{
    public
    FinancialNewsReceiverHolder()
    {
    }

    public
    FinancialNewsReceiverHolder(FinancialNewsReceiver value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof FinancialNewsReceiver)
        {
            value = (FinancialNewsReceiver)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _FinancialNewsReceiverDisp.ice_staticId();
    }
}
